SELECT
	COUNT(DISTINCT s.ID) "STRUCTURE_COUNT"
FROM
	APP.STRUCTURES AS s
	;
--
SELECT
	COUNT(DISTINCT s.ID) "ACTIVE_INGREDIENT_STRUCTURE_COUNT"
FROM
	APP.ACTIVE_INGREDIENT AS a,
	APP.STRUCTURES AS s
WHERE
	a.STRUCT_ID = s.ID
	;
--
SELECT
	p.PRODUCT_NAME,
	COUNT(DISTINCT s.ID) "ACTIVE_INGREDIENT_COUNT"
FROM
	APP.PRODUCT AS p,
	APP.ACTIVE_INGREDIENT AS a,
	APP.STRUCTURES AS s
WHERE
	UPPER(p.PRODUCT_NAME) LIKE '%ASPIRIN%'
	AND p.NDC_PRODUCT_CODE = a.NDC_PRODUCT_CODE
	AND a.STRUCT_ID = s.ID
GROUP BY
	p.PRODUCT_NAME
ORDER BY
	ACTIVE_INGREDIENT_COUNT
	;
--
-- UPPER(p.PRODUCT_NAME) LIKE '%LIPITOR%'
--
