--
SELECT DISTINCT
	ai.STRUCT_ID,
	ai.ACTIVE_MOIETY_NAME,
	ai.SUBSTANCE_NAME
FROM
	APP.ACTIVE_INGREDIENT AS ai
WHERE
	UPPER(ai.SUBSTANCE_NAME) LIKE '%ASPIRIN%'
ORDER BY
	LENGTH(ai.ACTIVE_MOIETY_NAME),
	ai.STRUCT_ID
	;
--
SELECT DISTINCT
	ai.STRUCT_ID,
	ai.ACTIVE_MOIETY_NAME,
	ai.SUBSTANCE_NAME,
	s.CAS_REG_NO,
	s.CD_SMILES
FROM
	APP.ACTIVE_INGREDIENT AS ai,
	APP.STRUCTURES AS s
WHERE
	ai.STRUCT_ID = s.ID
	AND UPPER(ai.SUBSTANCE_NAME) LIKE '%ASPIRIN%'
ORDER BY
	LENGTH(s.CD_SMILES),
	ai.STRUCT_ID
	;
--
SELECT
	s.ID,
	SUBSTR(s.NAME,1,80) "STRUCT_NAME",
	syn.NAME "SYNONYM"
FROM
	APP.STRUCTURES AS s,
	APP.SYNONYMS AS syn
WHERE
	syn.ID = s.ID
	AND UPPER(syn.NAME) LIKE '%ASPIRIN%'
	;
--
SELECT
	s.ID,
	SUBSTR(s.NAME,1,80) "STRUCT_NAME",
	syn.NAME "SYNONYM"
FROM
	APP.STRUCTURES AS s,
	APP.SYNONYMS AS syn
WHERE
	syn.ID = s.ID
	AND UPPER(syn.NAME) LIKE '%KETOROLAC%'
	;
--
--
--SELECT
--	syn1.ID,
--	syn2.NAME,
--	SUBSTR(s.NAME,1,80) "STRUCT_NAME",
--	SUBSTR(s.CD_SMILES,1,80) "SMILES"
--FROM
--	APP.SYNONYMS AS syn1,
--	APP.SYNONYMS AS syn2,
--	APP.STRUCTURES AS s
--WHERE
--	UPPER(syn1.NAME) LIKE '%ASPIRIN%'
--	AND syn1.ID = s.ID
--	AND syn1.ID = syn2.ID
--ORDER BY
--	LENGTH(syn2.NAME),
--	syn1.ID
--	;
--
