SELECT DISTINCT
	p.ID,
	p.PRODUCT_NAME,
	p.GENERIC_NAME,
	s.ID "STRUCT_ID",
	s.NAME,
	s.CD_SMILES
FROM
	APP.PRODUCT AS p,
	APP.ACTIVE_INGREDIENT AS a,
	APP.STRUCTURES AS s
WHERE
	UPPER(p.PRODUCT_NAME) LIKE '%ASPIRIN%'
	AND p.NDC_PRODUCT_CODE = a.NDC_PRODUCT_CODE
	AND a.STRUCT_ID = s.ID
	;
--
-- UPPER(p.PRODUCT_NAME) LIKE '%LIPITOR%'
--
SELECT
	p.ID,
	p.NDC_PRODUCT_CODE,
	p.FORM,
	p.GENERIC_NAME,
	p.PRODUCT_NAME,
	p.ROUTE,
	p.MARKETING_STATUS,
	p.ACTIVE_INGREDIENT_COUNT,
	ai.ACTIVE_MOIETY_NAME,
	ai.SUBSTANCE_NAME,
	s.CAS_REG_NO,
	s.CD_SMILES,
	s.CD_STRUCTURE,
	n.NAME "SYNONYM"
FROM
	APP.PRODUCT AS p,
	APP.ACTIVE_INGREDIENT AS ai,
	APP.STRUCTURES AS s,
	APP.SYNONYMS AS n
WHERE 
	p.NDC_PRODUCT_CODE = ai.NDC_PRODUCT_CODE
	AND ai.STRUCT_ID = s.ID
	AND n.ID = s.ID
	AND UPPER(p.PRODUCT_NAME) LIKE '%LIPITOR%'
	;
--
--
SELECT
	p.ID,
	p.NDC_PRODUCT_CODE,
	p.FORM,
	p.GENERIC_NAME,
	p.PRODUCT_NAME,
	p.ROUTE,
	p.MARKETING_STATUS,
	p.ACTIVE_INGREDIENT_COUNT,
	ai.ACTIVE_MOIETY_NAME,
	ai.SUBSTANCE_NAME,
	s.CAS_REG_NO,
	s.CD_SMILES,
	s.CD_STRUCTURE,
	n.NAME "SYNONYM"
FROM
	APP.PRODUCT AS p,
	APP.ACTIVE_INGREDIENT AS ai,
	APP.STRUCTURES AS s,
	APP.SYNONYMS AS n
WHERE 
	p.NDC_PRODUCT_CODE = ai.NDC_PRODUCT_CODE
	AND ai.STRUCT_ID = s.ID
	AND n.ID = s.ID
	AND p.ID = 1092986
	;
--
