SELECT DISTINCT
	a.STRUCT_ID,
	s.NAME,
	a.RELATION,
	a.ACT_TYPE,
	a.ACT_VALUE,
	a.ACT_UNIT,
	td.ID "TARGET_ID",
	td.NAME,
	td.CLASS,
	td.PROTEIN_TYPE,
	tc.ACCESSION,
	tc.SWISSPROT,
	tc.ORGANISM,
	tc.GENE,
	tc.GENEID,
	tc.NAME
FROM
	APP.STRUCTURES AS s,
	APP.ACTIVITIES AS a,
	APP.TARGET_DICTIONARY AS td,
	APP.TARGET_COMPONENT AS tc,
	APP.TD2TC AS td2tc
WHERE
	s.ID = a.STRUCT_ID
	AND a.TARGET_ID = td.ID
	AND td.ID = td2tc.TARGET_ID
	AND tc.ID = td2tc.COMPONENT_ID
	AND UPPER(s.NAME) LIKE '%TAMOXIFEN%'
	;
