SELECT DISTINCT
	ACTIVE_MOIETY_NAME,
	SUBSTANCE_NAME,
	ACTIVE_MOIETY_UNII,
	SUBSTANCE_UNII,
	CD_SMILES
FROM
	APP.ACTIVE_INGREDIENT,
	APP.STRUCTURES
WHERE
	ACTIVE_MOIETY_UNII IN ( 'U5N7SU872W', 'R16CO5Y76E' )
	AND ACTIVE_INGREDIENT.STRUCT_ID = STRUCTURES.ID
	;
